### ISSUE TITLE
Tested compilers?

### ISSUE THREAD

**Issue by Haider-BA** [luanmingyi/ordered_tec#2]
Which compilers tested for running ordered_tec? I have successfully used with **Visual Studio 2015** but getting some errors when running on **Code::Blocks**  (GNU GCC Compiler). The error is:

`\ordered_tec.h|104|error: could not convert 'std::basic_ofstream<char>()' from 'std::ofstream {aka std::basic_ofstream<char>}' to 'std::ofstream& {aka std::basic_ofstream<char>&}'|`

**Comment by luanmingyi** [comment]
the newest version can be compiled by g++ on ubuntu, so the problem may be solved

**Comment by luanmingyi** [comment]
the newest version can be compiled by g++ on ubuntu, so the problem may be solved

**Comment by Haider-BA** [comment]
Thank you.
